{
    'name': 'MML Freight Orchestration',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Freight tender, quote, booking and tracking for inbound POs',
    'author': 'MML',
    'license': 'OPL-1',
    'depends': [
        'mml_base',
        'mail',
        'stock',
        'account',
        'purchase',
        'delivery',
        'stock_account',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'views/freight_carrier_contract_views.xml',
        'views/freight_carrier_views.xml',
        'views/freight_tender_views.xml',
        'views/freight_booking_views.xml',
        'views/purchase_order_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mml_freight/static/src/scss/freight_views.scss',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
